cd ./exercise-01 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-02 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-03 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-04 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-06 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-08 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-09 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-10 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-11 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
cd ./exercise-12 && gradle idea && rm -f ./*.ipr && rm -f ./*.iws && cd ..
